AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Creates a Route 53 Hosted Zone and requests a validated ACM Certificate
  for the application's FQDN, exporting their IDs for use in the main stack.

Parameters:
  BaseDomainName:
    Type: String
    Description: The root domain name for the hosted zone (e.g., example.com).

  AppDomainName:
    Type: String
    Description: The fully qualified domain name (FQDN) for the application endpoint (e.g., api.example.com).

Resources:

  # 1. Route 53 Hosted Zone
  # This is the container for DNS records for the domain.
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref BaseDomainName
      HostedZoneConfig:
        Comment: Hosted zone for the application domain.

  # 2. ACM Certificate Request
  # Requests a certificate for the application's specific FQDN.
  AppCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref AppDomainName
      ValidationMethod: DNS
      # SubjectAlternativeNames is a list, but since we are only requesting one domain, we can omit it
      # or explicitly list the AppDomainName.
      DomainValidationOptions:
        - DomainName: !Ref AppDomainName
          HostedZoneId: !Ref HostedZone # Links validation to the created Hosted Zone

  # 3. ACM Certificate Validation Record Set Group
  # IMPORTANT FIX: This uses the required 'Route53:RecordSetGroup' structure
  # and the correct Fn::GetAtt syntax to access the validation record details.
  CertificateValidationRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZone
      # We use Fn::Join and Fn::GetAtt on the full array, which is supported
      RecordSets:
        - Name: !Join [ '', [ !GetAtt AppCertificate.DomainValidationOptions.0.ResourceRecord.Name, '.' ] ]
          Type: !GetAtt AppCertificate.DomainValidationOptions.0.ResourceRecord.Type
          TTL: '60'
          ResourceRecords:
            - !GetAtt AppCertificate.DomainValidationOptions.0.ResourceRecord.Value

  # 4. Wait for Certificate Validation
  # This resource links the certificate to the validation records, ensuring CFN waits
  # for the certificate status to become 'Issued' before proceeding.
  CertificateValidation:
    Type: AWS::CertificateManager::CertificateValidation
    Properties:
      CertificateArn: !Ref AppCertificate
      # This property requires a list of validation records, which we now get from the Route53 RecordSetGroup
      ValidationMethod: DNS
      DomainName: !Ref AppDomainName
      ValidationRecords:
        - !Ref CertificateValidationRecords

Outputs:
  HostedZoneId:
    Description: The ID of the Route 53 Hosted Zone.
    Value: !Ref HostedZone
    Export:
      Name: !Sub ${AppDomainName}-HostedZoneId

  CertificateArn:
    Description: The ARN of the validated ACM Certificate.
    Value: !Ref AppCertificate
    Export:
      Name: !Sub ${AppDomainName}-CertificateArn

  AppDomainName:
    Description: The FQDN used for the application.
    Value: !Ref AppDomainName
    Export:
      Name: !Sub ${AppDomainName}-FQDN
