AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to deploy a Next.js application to AWS ECS Fargate,
  including an Application Load Balancer with HTTPS (Port 443) and Route 53 integration.

Parameters:
  # --- Application Parameters ---
  AppName:
    Type: String
    Description: A unique name for your application. This will be used in resource names.
    Default: everything-booking-app

  ImageRepositoryName:
    Type: String
    Description: The name of your ECR repository (e.g., 'my-express-app-repo').
    Default: everything-booking-app-repo

  ImageTag:
    Type: String
    Description: The Docker image tag to deploy (e.g., 'latest' or a specific SHA from CI/CD).
    Default: latest

  ContainerPort:
    Type: Number
    Description: The port your application listens on inside the container (e.g., 3000).
    Default: 3000

  DesiredCount:
    Type: Number
    Description: The desired number of running tasks for your service.
    Default: 1

  ImportDomainName:
    Type: String
    Description: The FQDN used in the Network Setup Stack (e.g., api.bookingapp.com) to import resources.

  # --- Network Parameters ---
  VpcId:
    Type: String
    Description: The ID of the VPC where your resources will be deployed.

  SubnetIds:
    Type: CommaDelimitedList
    Description: A comma-separated list of PUBLIC subnet IDs for the ALB.

  PrivateSubnetIds:
    Type: CommaDelimitedList
    Description: A comma-separated list of PRIVATE subnet IDs for the ECS Tasks.

  # --- Resource Sizing Parameters ---
  TaskCpu:
    Type: String
    Description: The CPU units for the Fargate task.
    AllowedValues: [ "256", "512", "1024", "2048", "4096" ]
    Default: "256" # 0.25 vCPU

  TaskMemory:
    Type: String
    Description: The memory (in MiB) for the Fargate task. Must be compatible with TaskCpu.
    # See AWS Fargate documentation for valid CPU/Memory combinations.
    # For 256 CPU: 512, 1024, 2048
    # For 512 CPU: 1024, 2048, 3072, 4096
    # For 1024 CPU: 2048, 3072, 4096, 5120, 6144, 7168, 8192
    Default: "512" # 0.5 GB

  AppSecurityGroupId:
    Type: String
    Description: The ID of the Security Group for the App Tasks (must allow ingress from ALBSecurityGroup on port 3000).

# --- Imported Values ---
Mappings:
  ImportValues:
    HostedZoneId:
      Value: !ImportValue !Sub "${ImportDomainName}-HostedZoneId"
    CertificateArn:
      Value: !ImportValue !Sub "${ImportDomainName}-CertificateArn"
    AppDomainName:
      Value: !ImportValue !Sub "${ImportDomainName}-FQDN"

Resources:
  # --- IAM Roles ---
  # IAM Role for ECS Task Execution (Allows ECS to pull images, log to CloudWatch)
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Path: /
      Policies:
        - PolicyName: AllowSecretsManagerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                  - kms:Decrypt
                Resource: !Sub arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/everything-booking/env-variables*

  # IAM Role for ECS Task (If your application needs to interact with other AWS services, e.g., S3, DynamoDB)
  # For a simple Express app, this might not be strictly necessary, but it's good practice.
  EcsTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub ${AppName}-TaskAccessPolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/ecs/${AppName}-LogGroup:*

  # --- Log Group for ECS Tasks ---
  EcsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /ecs/${AppName}-LogGroup
      RetentionInDays: 7

  EcsCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${AppName}-Cluster

  # --- Application Load Balancer (ALB) ---
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: internet-facing
      Subnets: !Ref SubnetIds
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-ALB

  # ALB Target Group
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      HealthCheckPath: / # Ensure your Next.js app responds with 200 on this path
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      Matcher:
        HttpCode: '200'
      Port: !Ref ContainerPort
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-TargetGroup

  # --- ALB Listeners (Updated for HTTPS) ---

  # Listener on Port 443 (HTTPS) - Primary Listener
  HTTPSListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 443
      Protocol: HTTPS
      Certificates:
        - CertificateArn: !FindInMap [ImportValues, CertificateArn, Value]
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

  # Listener on Port 80 (HTTP) - Redirects all traffic to HTTPS
  HTTPListenerRedirect:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: 443
            StatusCode: HTTP_301 # Permanent redirect (best for SEO)

  # --- Route 53 RecordSet (NEW) ---
  AppDNS:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !FindInMap [ImportValues, HostedZoneId, Value] # IMPORTED ID
      Name: !FindInMap [ImportValues, AppDomainName, Value] # IMPORTED FQDN
      Type: A
      AliasTarget:
        # Point the domain name to the Load Balancer
        HostedZoneId: !GetAtt LoadBalancer.CanonicalHostedZoneID
        DNSName: !GetAtt LoadBalancer.DNSName

  # --- ECS Task Definition (Includes HOST=0.0.0.0 recommendation) ---
  EcsTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AppName}-TaskDefinition
      Cpu: !Ref TaskCpu
      Memory: !Ref TaskMemory
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt EcsTaskExecutionRole.Arn
      TaskRoleArn: !GetAtt EcsTaskRole.Arn
      ContainerDefinitions:
        - Name: !Sub ${AppName}-Container
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ImageRepositoryName}:${ImageTag}
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: !Ref ContainerPort # Not strictly needed for Fargate, but good practice
              Protocol: tcp
          Secrets:
            - name: DATABASE_URL
              valueFrom: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/everything-booking/env-variables:DATABASE_URL::"
            - name: AUTH_SECRET
              valueFrom: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:prod/everything-booking/env-variables:AUTH_SECRET::"
          Environment:
            - Name: NODE_ENV
              Value: production
            - Name: HOST # CRITICAL for Node/Next.js in Docker
              Value: 0.0.0.0
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref EcsLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs

  # --- ECS Service ---
  EcsService:
    Type: AWS::ECS::Service
    DependsOn: HTTPSListener # Depend on the new HTTPS Listener
    Properties:
      Cluster: !Ref EcsCluster
      ServiceName: !Sub ${AppName}-Service
      TaskDefinition: !Ref EcsTaskDefinition
      DesiredCount: !Ref DesiredCount # Integer Ref
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          Subnets: !Ref PrivateSubnetIds
          # FIX: SecurityGroups must be a list/JSONArray
          SecurityGroups:
            - !Ref AppSecurityGroupId
      LoadBalancers:
        - ContainerName: !Sub ${AppName}-Container
          ContainerPort: !Ref ContainerPort # Integer Ref
          TargetGroupArn: !Ref TargetGroup
      # HealthCheckGracePeriodSeconds must be an integer (60 is correct)
      HealthCheckGracePeriodSeconds: 60 
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
        DeploymentCircuitBreaker:
          Enable: true 
          Rollback: true
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-Service

Outputs:
  ClusterName:
    Description: The name of the ECS Cluster
    Value: !Ref EcsCluster
    Export:
      Name: !Sub ${AppName}-ClusterName

  LoadBalancerDNS:
    Description: The DNS name of the Application Load Balancer
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Sub ${AppName}-LoadBalancerDNS

  AppURL:
    Description: The application URL via HTTPS
    Value: !Sub https://${ImportDomainName}
    Export:
      Name: !Sub ${AppName}-AppURL

  ServiceArn:
    Description: The ARN of the ECS Service
    Value: !Ref EcsService
    Export:
      Name: !Sub ${AppName}-ServiceArn
